/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dc;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatGrayIJTheme;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.JFileChooser;
import Modelo.ConexionSQL;
import java.sql.Connection;
import Controlador.ControladorExcel;
import configuracion.config;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class Dashboard extends javax.swing.JFrame {

    ControladorExcel controlador;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitStyles();
        cargarBotonesGuardados();
                refrescar.addActionListener(e -> refrescarBarraLateral());
        
    }

    private void InitStyles() {
    
//        Info.putClientProperty( "FlatLaf.style", "font: 8% $light.font" );
  //      Info.setForeground(Color.white);
        jLabelTitulo.putClientProperty( "FlatLaf.style", "font: 200% $bold.font" );
        jLabelTitulo.setForeground(Color.white);
        txtBuscar.putClientProperty("JComponent.roundRect", true);
        txtBuscar.putClientProperty("JTextField.placeholderText", "Buscar matrícula, nómina o cédula...");
        txtBuscar.putClientProperty("JTextField.showClearButton", true);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        refrescar = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        BtImport = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        contenedorPestanas = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosExel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(45, 85, 154));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportView(jPanel2);

        jPanel2.setBackground(new java.awt.Color(45, 85, 154));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jButton5.setBackground(new java.awt.Color(21, 101, 192));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-statistics-25.png"))); // NOI18N
        jButton5.setText("Datos Institucionales");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-statistics-25.png")))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(21, 101, 192));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-user-male-25.png"))); // NOI18N
        jButton6.setText("Matrícula Estudiantil");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-add-user-male-25.png")))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(21, 101, 192));
        jButton7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-heart-with-pulse-25.png"))); // NOI18N
        jButton7.setText("Salud Y Bienes");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-heart-with-pulse-25.png")))); // NOI18N
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(21, 101, 192));
        jButton8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-database-25.png"))); // NOI18N
        jButton8.setText("Nómina RAC");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-database-25.png")))); // NOI18N
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setHideActionText(true);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton8);

        jScrollPane1.setViewportView(jPanel2);

        jButton1.setBackground(new java.awt.Color(21, 101, 192));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-file-25.png"))); // NOI18N
        jButton1.setText("Crear Botón Nuevo");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-add-file-25.png")))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(21, 101, 192));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-file-25.png"))); // NOI18N
        jButton3.setText("Eliminar Botón");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-file-25.png")))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(21, 101, 192));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-25.png"))); // NOI18N
        jButton4.setText("Editar Botón");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-25.png")))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setBorder(null);

        jButton12.setBackground(new java.awt.Color(45, 85, 154));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoDICI.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);

        jButton10.setBackground(new java.awt.Color(21, 101, 192));
        jButton10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-gear-25.png"))); // NOI18N
        jButton10.setText("Configuracion");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new javax.swing.ImageIcon(getClass().getResource("/icons8-gear-25.png")))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        refrescar.setBackground(new java.awt.Color(45, 85, 154));
        refrescar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-rotate-right-20.png"))); // NOI18N
        refrescar.setBorder(null);
        refrescar.setBorderPainted(false);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton12))
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton9))
                    .addComponent(refrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButton12)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(21, 101, 192));

        jLabelTitulo.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        jLabelTitulo.setText("Bienvenido a DICI");

        BtImport.setBackground(new java.awt.Color(45, 85, 154));
        BtImport.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtImport.setForeground(new java.awt.Color(255, 255, 255));
        BtImport.setText("Importar");
        BtImport.setBorder(null);
        BtImport.setBorderPainted(false);
        BtImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImportActionPerformed(evt);
            }
        });

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnCerrarSesion.setBackground(new java.awt.Color(45, 85, 154));
        btnCerrarSesion.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setText("Cerrar Sesion");
        btnCerrarSesion.setBorder(null);
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(226, 226, 226)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(BtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DatosExel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DatosExel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(DatosExel);

        contenedorPestanas.addTab("Documentos", jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPestanas)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(contenedorPestanas)
                .addContainerGap())
        );

        contenedorPestanas.getAccessibleContext().setAccessibleName("Lista de docucmentos ");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                                
        // Botón: Datos Institucionales -> Plantilla ID: 1
        if (controlador != null) {
            controlador.cambiarSeccion(1, "Datos Institucionales");
          actualizarEstadoMenu(jButton5, "Datos Institucionales");
        }
    }//GEN-LAST:event_jButton5ActionPerformed
 private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                
        // Botón: Datos Institucionales -> Plantilla ID: 1
        if (controlador != null) {
            controlador.cambiarSeccion(2, "Matricula Estudiantil");
            actualizarEstadoMenu(jButton6, "Matricula Estudiantil");
        }
          }
  private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                
        // Botón: Datos Institucionales -> Plantilla ID: 1
        if (controlador != null) {
            controlador.cambiarSeccion(3, "Salud y Bienes");
            actualizarEstadoMenu(jButton7, "Salud y Bienes");
        }
          }
   private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
                                
        // Botón: Datos Institucionales -> Plantilla ID: 1
        if (controlador != null) {
            controlador.cambiarSeccion(4, "Nòmina RAC");
            actualizarEstadoMenu(jButton8, "Nòmina RAC");
        }
          }
    private void BtImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImportActionPerformed
     
    // RESPUESTA AL BOTÓN DE IMPORTAR
        // TIENE UN TEMPORIZADOR PARA ACTIVAR LA FUNCION DE LA IMPORTACION GUARDA LO IMPORTADA EN UNA TABLAEXCEL 
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
               
                guardarDatosEnSQLite();
            }
        });
        timer.setRepeats(false); 
        timer.start();
    }                                        

    // MÉTODO QUE VACÍA LA BASE DE DATOS Y RESPALDA LA TABLA ACTUAL
   
    private void guardarDatosEnSQLite() {
    // 1. Validar si la tabla tiene información cargada
    if (DatosExel == null || DatosExel.getRowCount() == 0) {
        System.out.println("Guardado automático omitido: La tabla DatosExel está vacía.");
        return;
    }

    java.sql.Connection con = Modelo.ConexionSQL.getConexion();
    
    try {
        // Desactivamos el autocommit para procesar en lote de forma segura
        con.setAutoCommit(false);
        
        // 2. OBTENER LOS NOMBRES DE LAS COLUMNAS DE LA JTABLE
        int totalColumnas = DatosExel.getColumnCount();
        int totalFilas = DatosExel.getRowCount();
        String[] nombresColumnas = new String[totalColumnas];
        
        for (int col = 0; col < totalColumnas; col++) {
           
            String nombreLimpio = DatosExel.getColumnName(col)
                                    .trim()
                                    .replaceAll("[^a-zA-Z0-9_]", "_");
            
            // Si por algún motivo el encabezado está vacío, le asignamos un nombre genérico
            if (nombreLimpio.isEmpty()) {
                nombreLimpio = "columna_" + (col + 1);
            }
            nombresColumnas[col] = nombreLimpio;
        }

        // 3. BORRAR LA TABLA ANTERIOR SI EXISTE 
        String nombreTablaDinamica = "excel_importado";
        try (java.sql.Statement stmtDrop = con.createStatement()) {
            stmtDrop.execute("DROP TABLE IF EXISTS " + nombreTablaDinamica + ";");
        }

        // Armamos la consulta concatenando los nombres que extrajimos de la JTable
        StringBuilder sqlCreate = new StringBuilder("CREATE TABLE " + nombreTablaDinamica + " (");
        sqlCreate.append("id_registro INTEGER PRIMARY KEY AUTOINCREMENT, ");
        
        for (int col = 0; col < totalColumnas; col++) {
            sqlCreate.append(nombresColumnas[col]).append(" TEXT");
            if (col < totalColumnas - 1) {
                sqlCreate.append(", ");
            }
        }
        sqlCreate.append(");");

        // Ejecutamos la creación de la nueva tabla estructurada idéntica al Excel
        try (java.sql.Statement stmtCreate = con.createStatement()) {
            stmtCreate.execute(sqlCreate.toString());
        }

        // 5. CONSTRUIR EL 'INSERT' DINÁMICO
        StringBuilder sqlInsert = new StringBuilder("INSERT INTO " + nombreTablaDinamica + " (");
        StringBuilder valoresSignos = new StringBuilder();
        
        for (int col = 0; col < totalColumnas; col++) {
            sqlInsert.append(nombresColumnas[col]);
            valoresSignos.append("?");
            if (col < totalColumnas - 1) {
                sqlInsert.append(", ");
                valoresSignos.append(", ");
            }
        }
        sqlInsert.append(") VALUES (").append(valoresSignos).append(");");

        // 6. INSERTAR LOS DATOS FILA POR FILA
        try (java.sql.PreparedStatement psInsertar = con.prepareStatement(sqlInsert.toString())) {
            for (int fila = 0; fila < totalFilas; fila++) {
                for (int col = 0; col < totalColumnas; col++) {
                    Object valorCelda = DatosExel.getValueAt(fila, col);
                    String texto = (valorCelda != null) ? valorCelda.toString() : "";
                    
                    psInsertar.setString(col + 1, texto);
                }
                psInsertar.addBatch(); // Lo añadimos al lote
            }
            psInsertar.executeBatch(); // Guardado masivo veloz
        }

        // Confirmamos de forma definitiva en el archivo dici_sistema.db
        con.commit(); 

        // 7. AVISO DE ÉXITO DINÁMICO
        javax.swing.JOptionPane.showMessageDialog(this,
            "¡Estructura detectada y guardada con éxito!\n" +
            "Se creó la tabla '" + nombreTablaDinamica + "' con " + totalColumnas + " columnas y " + totalFilas + " filas.",
            "DICI - Importador Inteligente",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        try { con.rollback(); } catch (java.sql.SQLException ex) {}
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al estructurar dinámicamente la base de datos: " + e.getMessage(),
            "Error de Mapeo Dinámico",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try { con.setAutoCommit(true); } catch (java.sql.SQLException e) {}
    }

                                       
    }//GEN-LAST:event_BtImportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Preguntar el nombre al usuario
        String nombreBoton = javax.swing.JOptionPane.showInputDialog(
                this,
                "Ingrese el nombre del nuevo botón:",
                "Crear Nuevo Botón",
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (nombreBoton == null || nombreBoton.trim().isEmpty()) {
            return;
        }
        String nombreLimpio = nombreBoton.trim();

        // 2. Validar longitud
        if (nombreLimpio.length() > 20) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "El nombre es demasiado largo (Máximo 20 caracteres).",
                    "Nombre muy largo",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Connection con = ConexionSQL.getConexion();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Validar que el nombre no exista en la BD (ni en las predeterminadas)
        try {
            String sqlCheckNombre = "SELECT 1 FROM plantillas WHERE nombre_plantilla = ?";
            try (PreparedStatement ps = con.prepareStatement(sqlCheckNombre)) {
                ps.setString(1, nombreLimpio);
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this,
                            "Ya existe una sección llamada '" + nombreLimpio + "' en la base de datos.",
                            "Nombre duplicado",
                            JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al validar nombre: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Obtener el próximo ID disponible (máximo + 1)
        int nuevoIdPlantilla = 5; // fallback
        try {
            String sqlMaxId = "SELECT MAX(id_plantilla) + 1 FROM plantillas";
            try (Statement stmt = con.createStatement(); ResultSet rs = stmt.executeQuery(sqlMaxId)) {
                if (rs.next()) {
                    nuevoIdPlantilla = rs.getInt(1);
                    if (nuevoIdPlantilla < 5) {
                        nuevoIdPlantilla = 5;
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener ID: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 5. Registrar la plantilla en la BD
        try {
            String sqlInsert = "INSERT INTO plantillas (id_plantilla, nombre_plantilla) VALUES (?, ?)";
            try (PreparedStatement ps = con.prepareStatement(sqlInsert)) {
                ps.setInt(1, nuevoIdPlantilla);
                ps.setString(2, nombreLimpio);
                ps.executeUpdate();
                System.out.println("Plantilla registrada con ID: " + nuevoIdPlantilla);
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al registrar la sección: " + e.getMessage(), "Error BD", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 6. Crear el botón visual
        javax.swing.JButton nuevoBoton = new javax.swing.JButton(nombreLimpio);
        nuevoBoton.setBackground(new java.awt.Color(21, 101, 192));
        nuevoBoton.setForeground(new java.awt.Color(255, 255, 255));
        nuevoBoton.setFont(new java.awt.Font("sansserif", 1, 14));
        nuevoBoton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nuevoBoton.setContentAreaFilled(true);
        nuevoBoton.setBorderPainted(false);
        nuevoBoton.setFocusPainted(false);
        nuevoBoton.setMinimumSize(new java.awt.Dimension(180, 50));
        nuevoBoton.setPreferredSize(new java.awt.Dimension(180, 50));
        nuevoBoton.setMaximumSize(new java.awt.Dimension(340, 50));
        nuevoBoton.setAlignmentX(0.0f);

        // Obtener cantidad actual de botones en el .properties (para posicionar)
        Properties props = new Properties();
        File archivo = new File("botones_personalizados.properties");
        if (archivo.exists()) {
            try (FileInputStream fis = new FileInputStream(archivo)) {
                props.load(fis);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        int cantidadBotones = 0;
        while (props.containsKey("boton_" + cantidadBotones)) {
            cantidadBotones++;
        }

        int posicionInsersion = 4 + cantidadBotones;
        if (jPanel2.getComponentCount() < posicionInsersion) {
            posicionInsersion = jPanel2.getComponentCount();
        }

        nuevoBoton.putClientProperty("id_plantilla", nuevoIdPlantilla);

        nuevoBoton.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (controlador != null) {
                    int id = (int) nuevoBoton.getClientProperty("id_plantilla");
                    String nombreSeccion = nuevoBoton.getText();
                    controlador.cambiarSeccion(id, nombreSeccion);
                    actualizarEstadoMenu(nuevoBoton, nombreSeccion);
                }
            }
        });

        jPanel2.add(nuevoBoton, posicionInsersion);
        jPanel2.revalidate();
        jPanel2.repaint();

        // 7. Guardar en el archivo .properties con su ID
        guardarBotonEnArchivo(nombreLimpio, nuevoIdPlantilla);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    java.util.Properties props = new java.util.Properties();
    java.io.File archivo = new java.io.File("botones_personalizados.properties");

    if (!archivo.exists()) {
        JOptionPane.showMessageDialog(this, "No hay botones personalizados para eliminar.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 1. Cargar los botones actuales desde el archivo
    try (java.io.FileInputStream fis = new java.io.FileInputStream(archivo)) {
        props.load(fis);
    } catch (java.io.IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al leer el archivo de configuración.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 🔥 CALCULAR CUÁNTOS BOTONES REALES HAY (sin contar las claves .id)
    int cantidadBotones = 0;
    while (props.containsKey("boton_" + cantidadBotones)) {
        cantidadBotones++;
    }

    if (cantidadBotones == 0) {
        JOptionPane.showMessageDialog(this, "No hay botones personalizados para eliminar.", "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 2. Pasar los nombres de los botones a un arreglo
    String[] nombresBotones = new String[cantidadBotones];
    for (int i = 0; i < cantidadBotones; i++) {
        nombresBotones[i] = props.getProperty("boton_" + i);
    }

    // 3. Preguntar al usuario cuál desea borrar
    String botonSeleccionado = (String) JOptionPane.showInputDialog(
            this,
            "Seleccione el botón que desea eliminar:",
            "Eliminar Botón",
            JOptionPane.QUESTION_MESSAGE,
            null,
            nombresBotones,
            nombresBotones[0]
    );

    if (botonSeleccionado == null) return;

    int indiceAEliminar = -1;
    for (int i = 0; i < cantidadBotones; i++) {
        if (nombresBotones[i].equals(botonSeleccionado)) {
            indiceAEliminar = i;
            break;
        }
    }

    if (indiceAEliminar == -1) return;

    // 🔥 OBTENER EL ID REAL DE LA PLANTILLA (desde el .properties si existe, o calcular)
    int idPlantillaABorrar = 5 + indiceAEliminar; // valor por defecto
    String idProp = props.getProperty("boton_" + indiceAEliminar + ".id");
    if (idProp != null) {
        try {
            idPlantillaABorrar = Integer.parseInt(idProp);
        } catch (NumberFormatException e) {
            // fallback
        }
    }

    Connection con = ConexionSQL.getConexion();

    if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. Eliminar de la base de datos
    try {
        con.setAutoCommit(false);

        // Desactivar restricciones temporalmente
        try (java.sql.Statement stmt = con.createStatement()) {
            stmt.execute("PRAGMA foreign_keys = OFF;");
        }

        // Eliminar valores_celda de documentos de esta plantilla
        String sqlDeleteValores = "DELETE FROM valores_celda WHERE id_documento IN (SELECT id_documento FROM documentos_planilla WHERE id_plantilla = ?)";
        try (java.sql.PreparedStatement psDeleteV = con.prepareStatement(sqlDeleteValores)) {
            psDeleteV.setInt(1, idPlantillaABorrar);
            psDeleteV.executeUpdate();
            System.out.println("✅ Valores_celda eliminados para plantilla " + idPlantillaABorrar);
        }

        // Eliminar documentos_planilla de esta plantilla
        String sqlDeleteFormatos = "DELETE FROM documentos_planilla WHERE id_plantilla = ?";
        try (java.sql.PreparedStatement psDeleteF = con.prepareStatement(sqlDeleteFormatos)) {
            psDeleteF.setInt(1, idPlantillaABorrar);
            psDeleteF.executeUpdate();
            System.out.println("✅ Documentos eliminados para plantilla " + idPlantillaABorrar);
        }

        // Eliminar campos_plantilla de esta plantilla
        String sqlDeleteCampos = "DELETE FROM campos_plantilla WHERE id_plantilla = ?";
        try (java.sql.PreparedStatement psDeleteC = con.prepareStatement(sqlDeleteCampos)) {
            psDeleteC.setInt(1, idPlantillaABorrar);
            psDeleteC.executeUpdate();
            System.out.println("✅ Campos eliminados para plantilla " + idPlantillaABorrar);
        }

        // Eliminar la plantilla
        String sqlDeletePlantilla = "DELETE FROM plantillas WHERE id_plantilla = ?";
        try (java.sql.PreparedStatement psDeleteP = con.prepareStatement(sqlDeletePlantilla)) {
            psDeleteP.setInt(1, idPlantillaABorrar);
            psDeleteP.executeUpdate();
            System.out.println("✅ Plantilla " + idPlantillaABorrar + " eliminada");
        }

        // Reactivar restricciones
        try (java.sql.Statement stmt = con.createStatement()) {
            stmt.execute("PRAGMA foreign_keys = ON;");
        }

        con.commit();
        System.out.println("✅ BD sincronizada: Plantilla eliminada correctamente.");

    } catch (java.sql.SQLException e) {
        try {
            try (java.sql.Statement stmt = con.createStatement()) {
                stmt.execute("PRAGMA foreign_keys = ON;");
            }
            con.rollback();
        } catch (java.sql.SQLException ex) {
            ex.printStackTrace();
        }

        System.err.println("❌ Error en la transacción: " + e.getMessage());
        e.printStackTrace();
        JOptionPane.showMessageDialog(this,
                "Error al eliminar: " + e.getMessage(),
                "Error BD", JOptionPane.ERROR_MESSAGE);
        return;
    } finally {
        try {
            con.setAutoCommit(true);
        } catch (java.sql.SQLException ex) {
            ex.printStackTrace();
        }
    }

    // 5. Reestructurar el archivo .properties (USANDO EL CONTADOR REAL)
    java.util.Properties nuevasProps = new java.util.Properties();
    int nuevoContador = 0;
    for (int i = 0; i < cantidadBotones; i++) {
        if (i != indiceAEliminar) {
            // Copiar el nombre
            nuevasProps.setProperty("boton_" + nuevoContador, nombresBotones[i]);
            // Copiar el ID si existe
            String idOrig = props.getProperty("boton_" + i + ".id");
            if (idOrig != null) {
                nuevasProps.setProperty("boton_" + nuevoContador + ".id", idOrig);
            }
            nuevoContador++;
        }
    }

    try (java.io.FileOutputStream fos = new java.io.FileOutputStream(archivo)) {
        nuevasProps.store(fos, "Botones creados por el usuario");
    } catch (java.io.IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar el archivo de configuración.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    refrescarBarraLateral();
    JOptionPane.showMessageDialog(this, "✅ Botón eliminado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                         
    java.util.Properties props = new java.util.Properties();
    java.io.File archivo = new java.io.File("botones_personalizados.properties");
    
    if (!archivo.exists()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay botones personalizados para editar.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // 1. Cargar las propiedades actuales
    try (java.io.FileInputStream fis = new java.io.FileInputStream(archivo)) {
        props.load(fis);
    } catch (java.io.IOException e) {
        e.printStackTrace();
    }
    
    if (props.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "No hay botones personalizados para editar.", "Información", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    String[] nombresBotones = new String[props.size()];
    for (int i = 0; i < props.size(); i++) {
        nombresBotones[i] = props.getProperty("boton_" + i);
    }
    
    // 2. Preguntar cuál botón quiere renombrar
    String botonSeleccionado = (String) javax.swing.JOptionPane.showInputDialog(
        this,
        "Seleccione el botón que desea editar:",
        "Editar Botón",
        javax.swing.JOptionPane.QUESTION_MESSAGE,
        null,
        nombresBotones,
        nombresBotones[0]
    );
    
    if (botonSeleccionado != null) {
        // 3. Pedir el nuevo nombre de carpeta al usuario
        String nuevoNombre = javax.swing.JOptionPane.showInputDialog(
            this,
            "Ingrese el nuevo nombre para el botón:",
            "Renombrar Botón",
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
        
        if (nuevoNombre != null && !nuevoNombre.trim().isEmpty()) {
            // Buscar la clave correspondiente y actualizarle el nombre de texto
            for (int i = 0; i < nombresBotones.length; i++) {
                if (nombresBotones[i].equals(botonSeleccionado)) {
                    props.setProperty("boton_" + i, nuevoNombre.trim());
                    break;
                }
            }
            
            // Guardar los cambios con el nuevo nombre de etiqueta en el archivo
            try (java.io.FileOutputStream fos = new java.io.FileOutputStream(archivo)) {
                props.store(fos, "Botones creados por el usuario");
            } catch (java.io.IOException e) {
                e.printStackTrace();
            }
            
            // 🌟 CLAVE: Refresca el panel lateral para cambiar el texto del botón visualmente 
            // manteniendo el mismo ID y la misma acción del controlador
            refrescarBarraLateral();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Botón actualizado correctamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        config nueva = new config();
        nueva.setLocationRelativeTo(null);
        nueva.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "¿Seguro que deseas cerrar sesión?", 
        "Cerrar Sesión", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );
    if (confirm == JOptionPane.YES_OPTION) {
        // Cerrar Dashboard
        this.dispose();
        // Abrir Login nuevamente
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    // Método para guardar el nombre del nuevo botón en archivo de texto de botones

private void guardarBotonEnArchivo(String nombre, int idPlantilla) {
    java.util.Properties props = new java.util.Properties();
    java.io.File archivo = new java.io.File("botones_personalizados.properties");
    
    if (archivo.exists()) {
        try (java.io.FileInputStream fis = new java.io.FileInputStream(archivo)) {
            props.load(fis);
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
    
    // Contar solo las claves "boton_X" (sin .id)
    int cantidadActual = 0;
    while (props.containsKey("boton_" + cantidadActual)) {
        cantidadActual++;
    }
    
    props.setProperty("boton_" + cantidadActual, nombre);
    props.setProperty("boton_" + cantidadActual + ".id", String.valueOf(idPlantilla));
    
    try (java.io.FileOutputStream fos = new java.io.FileOutputStream(archivo)) {
        props.store(fos, "Botones creados por el usuario");
    } catch (java.io.IOException e) {
        e.printStackTrace();
    }
}
private void cargarBotonesGuardados() {
    java.util.Properties props = new java.util.Properties();
    java.io.File archivo = new java.io.File("botones_personalizados.properties");
    
    if (archivo.exists()) {
        try (java.io.FileInputStream fis = new java.io.FileInputStream(archivo)) {
            props.load(fis);
            
            int i = 0;
            while (props.containsKey("boton_" + i)) {
                String nombreBoton = props.getProperty("boton_" + i);
                javax.swing.JButton nuevoBoton = new javax.swing.JButton(nombreBoton);
                
                // APARIENCIA
                nuevoBoton.setBackground(new java.awt.Color(21, 101, 192));
                nuevoBoton.setForeground(jButton8.getForeground());
                nuevoBoton.setFont(jButton8.getFont());
                nuevoBoton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                nuevoBoton.setIcon(jButton8.getIcon());
                nuevoBoton.setBorder(jButton8.getBorder());
                nuevoBoton.setContentAreaFilled(true);
                nuevoBoton.setBorderPainted(false);
                nuevoBoton.setFocusPainted(false);
                nuevoBoton.setMinimumSize(new java.awt.Dimension(180, 50));
                nuevoBoton.setPreferredSize(new java.awt.Dimension(180, 50));
                nuevoBoton.setMaximumSize(new java.awt.Dimension(340, 50));
                nuevoBoton.setAlignmentX(0.0f);
                
                int posicionInsersion = 4 + i;
                if (jPanel2.getComponentCount() < posicionInsersion) {
                    posicionInsersion = jPanel2.getComponentCount();
                }
                
                // 🔥 LEER EL ID REAL (si existe)
                int idPlantilla = 5 + i;
                String idProp = props.getProperty("boton_" + i + ".id");
                if (idProp != null) {
                    try {
                        idPlantilla = Integer.parseInt(idProp);
                    } catch (NumberFormatException e) {
                        // fallback
                    }
                }
                nuevoBoton.putClientProperty("id_plantilla", idPlantilla);
                
                nuevoBoton.addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        if (controlador != null) {
                            int id = (int) nuevoBoton.getClientProperty("id_plantilla");
                            String nombreSeccion = nuevoBoton.getText();
                            controlador.cambiarSeccion(id, nombreSeccion);
                            actualizarEstadoMenu(nuevoBoton, nombreSeccion);
                        }
                    }
                });
                
                jPanel2.add(nuevoBoton, posicionInsersion);
                i++;
            }
            
            jPanel2.revalidate();
            jPanel2.repaint();
            
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
    }
}

private void refrescarBarraLateral() {
    // Romueve los componentes de la posición 4 en adelante (los dinámicos)
    while (jPanel2.getComponentCount() > 4) {
        jPanel2.remove(4);
    }
    
    // Volver a leer el archivo .properties actualizado
    cargarBotonesGuardados();
    
    // Forzar a NetBeans y Swing a redibujar el panel
    jPanel2.revalidate();
    jPanel2.repaint();
}
public void actualizarEstadoMenu(javax.swing.JButton botonActivo, String nombreSeccion) {
    // 1. Cambiar el texto del título principal dinámicamente
    jLabelTitulo.setText("-" + nombreSeccion); 
    // Si tienes otra etiqueta más arriba para el estado secundario, la cambias aquí también.

    // 2. Definir los colores (Tu azul original y el color de "Seleccionado")
    java.awt.Color azulOriginal = new java.awt.Color(21, 101, 192);
    java.awt.Color azulSeleccionado = new java.awt.Color(13, 71, 161); // Un azul más oscuro elegante para resaltar

    // 3. Recorrer TODOS los componentes del panel izquierdo para limpiarlos
    for (java.awt.Component comp : jPanel2.getComponents()) {
        if (comp instanceof javax.swing.JButton) {
            javax.swing.JButton btn = (javax.swing.JButton) comp;
            
            // Excluimos los botones de acción como "Editar", "Eliminar" o "Crear Nuevo"
            String texto = btn.getText();
            if (!texto.equals("Editar Botón") && !texto.equals("Eliminar Botón") && !texto.equals("Crear Botón Nuevo")) {
                
                // Si es el botón que el usuario acaba de tocar, lo pintamos diferente
                if (btn == botonActivo) {
                    btn.setBackground(azulSeleccionado);
                } else {
                    // Si no, le devolvemos su color base
                    btn.setBackground(azulOriginal);
                }
            }
        }
    }
    
    // 4. Refrescar el panel para aplicar los cambios de color de inmediato
    jPanel2.revalidate();
    jPanel2.repaint();
}
    public static void main(String args[]) {
        // 1. Preparamos el tema visual de FlatLaf
        com.formdev.flatlaf.themes.FlatMacLightLaf.setup();

        /* Crear y mostrar el formulario */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // 2. Instanciamos el modelo visual de la tabla
                Modelo.ModeloExcel ModeloEX = new Modelo.ModeloExcel();

                // 3. Creamos la interfaz gráfica
                Dashboard VistaEX = new Dashboard();

                // 4. Creamos el controlador y le pasamos la vista y el modelo
                Controlador.ControladorExcel controladorExcel = new Controlador.ControladorExcel(VistaEX, ModeloEX);

                // 5. ¡Paso Clave! Le entregamos el controlador a la vista para que los botones funcionen
                VistaEX.controlador = controladorExcel;

                // 6. Hacemos visible la ventana principal
                VistaEX.setVisible(true);
            }
        
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtImport;
    public javax.swing.JTable DatosExel;
    public javax.swing.JButton btnCerrarSesion;
    public javax.swing.JTabbedPane contenedorPestanas;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    private javax.swing.JButton refrescar;
    public javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

// NUEVO CONSTRUCTOR que recibe el controlador
    public Dashboard(Controlador.ControladorExcel controlador) {
        initComponents();
        InitStyles();
        cargarBotonesGuardados();
        this.controlador = controlador;
    }
}