/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dc;

import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.intellijthemes.FlatGrayIJTheme;
import com.formdev.flatlaf.themes.FlatMacLightLaf;
import java.awt.Color;
import javax.swing.UIManager;
import javax.swing.JFileChooser;
import Modelo.ConexionSQL;
import java.sql.Connection;


/**
 *
 * @author carlos
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        InitStyles();
    }
    private void InitStyles() {
    
        Info.putClientProperty( "FlatLaf.style", "font: 8% $light.font" );
        Info.setForeground(Color.white);
        Welcome.putClientProperty( "FlatLaf.style", "font: 200% $bold.font" );
        Welcome.setForeground(Color.white);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        header = new javax.swing.JPanel();
        Info = new javax.swing.JLabel();
        Welcome = new javax.swing.JLabel();
        BtExport = new javax.swing.JButton();
        BtImport = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosExel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(255, 255, 255));

        menu.setBackground(new java.awt.Color(45, 85, 154));
        menu.setPreferredSize(new java.awt.Dimension(270, 640));

        jScrollPane1.setBorder(null);

        jPanel2.setBackground(new java.awt.Color(45, 85, 154));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jButton5.setBackground(new java.awt.Color(21, 101, 192));
        jButton5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-statistics-25.png"))); // NOI18N
        jButton5.setText("Datos Institucionales");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton5.setBorderPainted(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton5.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);

        jButton6.setBackground(new java.awt.Color(21, 101, 192));
        jButton6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-user-male-25.png"))); // NOI18N
        jButton6.setText("Matrícula Estudiantil");
        jButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton6.setBorderPainted(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton6.setMaximumSize(new java.awt.Dimension(340, 50));
        jPanel2.add(jButton6);

        jButton7.setBackground(new java.awt.Color(21, 101, 192));
        jButton7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-heart-with-pulse-25.png"))); // NOI18N
        jButton7.setText("Salud Y Bienes");
        jButton7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton7.setBorderPainted(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setMaximumSize(new java.awt.Dimension(340, 50));
        jPanel2.add(jButton7);

        jButton8.setBackground(new java.awt.Color(21, 101, 192));
        jButton8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-database-25.png"))); // NOI18N
        jButton8.setText("Nómina RAC");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setHideActionText(true);
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setMaximumSize(new java.awt.Dimension(340, 50));
        jPanel2.add(jButton8);

        jScrollPane1.setViewportView(jPanel2);

        jButton1.setBackground(new java.awt.Color(21, 101, 192));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-add-file-25.png"))); // NOI18N
        jButton1.setText("Crear Botón Nuevo");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton3.setBackground(new java.awt.Color(21, 101, 192));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-delete-file-25.png"))); // NOI18N
        jButton3.setText("Eliminar Botón");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton4.setBackground(new java.awt.Color(21, 101, 192));
        jButton4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-edit-25.png"))); // NOI18N
        jButton4.setText("Editar Botón");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton4.setBorderPainted(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton9.setBorder(null);

        jButton12.setBackground(new java.awt.Color(45, 85, 154));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoDICI.png"))); // NOI18N
        jButton12.setBorder(null);
        jButton12.setBorderPainted(false);

        jButton10.setBackground(new java.awt.Color(21, 101, 192));
        jButton10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-gear-25.png"))); // NOI18N
        jButton10.setText("Configuracion");
        jButton10.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton10.setBorderPainted(false);
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButton12))
                    .addComponent(jButton9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton9)
                .addGap(8, 8, 8)
                .addComponent(jButton12)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
        );

        header.setBackground(new java.awt.Color(21, 101, 192));

        Info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Info.setText("aQUI VA lA InFORMACION");

        Welcome.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        Welcome.setText("Bienvenido a DICI");

        BtExport.setBackground(new java.awt.Color(45, 85, 154));
        BtExport.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtExport.setForeground(new java.awt.Color(255, 255, 255));
        BtExport.setText("Exportar");
        BtExport.setBorder(null);
        BtExport.setBorderPainted(false);
        BtExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExportActionPerformed(evt);
            }
        });

        BtImport.setBackground(new java.awt.Color(45, 85, 154));
        BtImport.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BtImport.setForeground(new java.awt.Color(255, 255, 255));
        BtImport.setText("Importar");
        BtImport.setBorder(null);
        BtImport.setBorderPainted(false);
        BtImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Welcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(421, 421, 421)
                .addComponent(BtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(BtExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
            .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtExport, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Welcome)))
                .addGap(4, 4, 4)
                .addComponent(Info, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        DatosExel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DatosExel.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(DatosExel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
            .addGroup(fondoLayout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void BtImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImportActionPerformed
     
    // RESPUESTA AL BOTÓN DE IMPORTAR
        // TIENE UN TEMPORIZADOR PARA ACTIVAR LA FUNCION DE LA IMPORTACION GUARDA LO IMPORTADA EN UNA TABLAEXCEL 
        javax.swing.Timer timer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
               
                guardarDatosEnSQLite();
            }
        });
        timer.setRepeats(false); 
        timer.start();
    }                                        

    // MÉTODO QUE VACÍA LA BASE DE DATOS Y RESPALDA LA TABLA ACTUAL
   
    private void guardarDatosEnSQLite() {
    // 1. Validar si la tabla tiene información cargada
    if (DatosExel == null || DatosExel.getRowCount() == 0) {
        System.out.println("Guardado automático omitido: La tabla DatosExel está vacía.");
        return;
    }

    java.sql.Connection con = Modelo.ConexionSQL.getConexion();
    
    try {
        // Desactivamos el autocommit para procesar en lote de forma segura
        con.setAutoCommit(false);
        
        // 2. OBTENER LOS NOMBRES DE LAS COLUMNAS DE LA JTABLE
        int totalColumnas = DatosExel.getColumnCount();
        int totalFilas = DatosExel.getRowCount();
        String[] nombresColumnas = new String[totalColumnas];
        
        for (int col = 0; col < totalColumnas; col++) {
           
            String nombreLimpio = DatosExel.getColumnName(col)
                                    .trim()
                                    .replaceAll("[^a-zA-Z0-9_]", "_");
            
            // Si por algún motivo el encabezado está vacío, le asignamos un nombre genérico
            if (nombreLimpio.isEmpty()) {
                nombreLimpio = "columna_" + (col + 1);
            }
            nombresColumnas[col] = nombreLimpio;
        }

        // 3. BORRAR LA TABLA ANTERIOR SI EXISTE 
        String nombreTablaDinamica = "excel_importado";
        try (java.sql.Statement stmtDrop = con.createStatement()) {
            stmtDrop.execute("DROP TABLE IF EXISTS " + nombreTablaDinamica + ";");
        }

        // Armamos la consulta concatenando los nombres que extrajimos de la JTable
        StringBuilder sqlCreate = new StringBuilder("CREATE TABLE " + nombreTablaDinamica + " (");
        sqlCreate.append("id_registro INTEGER PRIMARY KEY AUTOINCREMENT, ");
        
        for (int col = 0; col < totalColumnas; col++) {
            sqlCreate.append(nombresColumnas[col]).append(" TEXT");
            if (col < totalColumnas - 1) {
                sqlCreate.append(", ");
            }
        }
        sqlCreate.append(");");

        // Ejecutamos la creación de la nueva tabla estructurada idéntica al Excel
        try (java.sql.Statement stmtCreate = con.createStatement()) {
            stmtCreate.execute(sqlCreate.toString());
        }

        // 5. CONSTRUIR EL 'INSERT' DINÁMICO
        StringBuilder sqlInsert = new StringBuilder("INSERT INTO " + nombreTablaDinamica + " (");
        StringBuilder valoresSignos = new StringBuilder();
        
        for (int col = 0; col < totalColumnas; col++) {
            sqlInsert.append(nombresColumnas[col]);
            valoresSignos.append("?");
            if (col < totalColumnas - 1) {
                sqlInsert.append(", ");
                valoresSignos.append(", ");
            }
        }
        sqlInsert.append(") VALUES (").append(valoresSignos).append(");");

        // 6. INSERTAR LOS DATOS FILA POR FILA
        try (java.sql.PreparedStatement psInsertar = con.prepareStatement(sqlInsert.toString())) {
            for (int fila = 0; fila < totalFilas; fila++) {
                for (int col = 0; col < totalColumnas; col++) {
                    Object valorCelda = DatosExel.getValueAt(fila, col);
                    String texto = (valorCelda != null) ? valorCelda.toString() : "";
                    
                    psInsertar.setString(col + 1, texto);
                }
                psInsertar.addBatch(); // Lo añadimos al lote
            }
            psInsertar.executeBatch(); // Guardado masivo veloz
        }

        // Confirmamos de forma definitiva en el archivo dici_sistema.db
        con.commit(); 

        // 7. AVISO DE ÉXITO DINÁMICO
        javax.swing.JOptionPane.showMessageDialog(this,
            "¡Estructura detectada y guardada con éxito!\n" +
            "Se creó la tabla '" + nombreTablaDinamica + "' con " + totalColumnas + " columnas y " + totalFilas + " filas.",
            "DICI - Importador Inteligente",
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

    } catch (Exception e) {
        try { con.rollback(); } catch (java.sql.SQLException ex) {}
        javax.swing.JOptionPane.showMessageDialog(this,
            "Error al estructurar dinámicamente la base de datos: " + e.getMessage(),
            "Error de Mapeo Dinámico",
            javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    } finally {
        try { con.setAutoCommit(true); } catch (java.sql.SQLException e) {}
    }

                                       
    }//GEN-LAST:event_BtImportActionPerformed

    private void BtExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtExportActionPerformed

  
    public static void main(String args[]) {
        // 1. Lo PRIMERO que hace el programa es preparar el tema visual
        com.formdev.flatlaf.themes.FlatMacLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // 2. Modelo de Excel de Ana
                Modelo.ModeloExcel ModeloEX = new Modelo.ModeloExcel();

                // 3. Creamos UNA SOLA instancia de la ventana (Ya tendrá el estilo Mac)
                Dashboard VistaEX = new Dashboard();

                // 4. Se la pasamos al controlador para que vincule la lógica de POI
                Controlador.ControladorExcel ControladorExcel = new Controlador.ControladorExcel(VistaEX, ModeloEX);

                // 5. Hacemos visible esa ÚNICA ventana controlada
                VistaEX.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtExport;
    public javax.swing.JButton BtImport;
    public javax.swing.JTable DatosExel;
    public javax.swing.JLabel Info;
    private javax.swing.JLabel Welcome;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
