/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package configuracion;

import com.mycompany.dc.*;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class Cambiar_Nombre extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Cambiar_Nombre() {
        initComponents();
        jButton4.addActionListener(e -> cambiarNombre());
        InitStyles();

    }
        private void InitStyles() {
        txtname1.putClientProperty("JTextField.placeholderText", "Escribe tu nombre actual");
        txtname1.putClientProperty("JTextField.showClearButton", true);
        txtname.putClientProperty("JTextField.placeholderText", "Escribe tu nuevo nombre");
        txtname.putClientProperty("JTextField.showClearButton", true);
        clave.putClientProperty("JTextField.placeholderText", "confirma con contraseña");
        clave.putClientProperty("JTextField.showClearButton", true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        clave = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        txtname1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(21, 101, 192));
        jButton4.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Confirmar");
        jButton4.setBorder(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dici16x16.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);

        title.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        title.setForeground(new java.awt.Color(153, 153, 153));
        title.setText("DICI");

        title2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        title2.setForeground(new java.awt.Color(61, 61, 61));
        title2.setText("Antes de continuar..");

        txtname.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-administrator-male-2522.png"))); // NOI18N
        jButton1.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-key-security-2522.png"))); // NOI18N
        jButton2.setBorder(null);

        clave.setBorder(null);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("<html> Antes de cambiar su nombre de usuario debe tener en cuenta lo siguiente:<br>\n 1. El equipo DICI no se hace responsable por nombres olvidados<br> \n 2. Recomendamos cambiar el usuario solo si este mismo esta comprometido<br> \n 3. Recuerde que no podemos recuperar nombres perdidos ni recuperar<br> \nla base de datos del usuario afectado</html>");

        jButton7.setBackground(new java.awt.Color(102, 102, 102));
        jButton7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cancelar");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        txtname1.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-administrator-male-2522.png"))); // NOI18N
        jButton3.setBorder(null);

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(FondoLayout.createSequentialGroup()
                                    .addComponent(jButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(FondoLayout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(clave))
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FondoLayout.createSequentialGroup()
                                .addGap(267, 267, 267)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(FondoLayout.createSequentialGroup()
                            .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(title2)
                                .addGroup(FondoLayout.createSequentialGroup()
                                    .addComponent(jButton5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(title)))
                            .addGap(246, 246, 246))))
                .addGap(50, 50, 50))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clave, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        config nueva = new config();
        nueva.setLocationRelativeTo(null);
        nueva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cambiar_Nombre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JPasswordField clave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    // End of variables declaration//GEN-END:variables


    private void cambiarNombre() {
    String usuarioActual = txtname1.getText().trim();     // 📌 Campo 1: Nombre actual
    String nuevoUsuario = txtname.getText().trim();       // 📌 Campo 2: Nuevo nombre
    String passActual = new String(clave.getPassword()).trim(); // 📌 Campo 3: Contraseña actual
    
    // ✅ Validaciones
    if (usuarioActual.isEmpty() || nuevoUsuario.isEmpty() || passActual.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    if (usuarioActual.equals(nuevoUsuario)) {
        JOptionPane.showMessageDialog(this, "El nuevo nombre debe ser diferente al actual", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (nuevoUsuario.length() < 3) {
        JOptionPane.showMessageDialog(this, "El nombre debe tener al menos 3 caracteres", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 🔐 Hashear la contraseña actual para comparar
    String hashIngresado = Modelo.baseInicial.encriptarSHA256(passActual);
    
    Connection con = Modelo.ConexionSQL.getConexion();
    if (con == null) {
        JOptionPane.showMessageDialog(this, "Error de conexión a la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // 🔍 PASO 1: Verificar que el usuario actual existe y la contraseña es correcta
        String sqlVerificar = "SELECT id_usuario FROM usuarios WHERE username = ? AND password = ?";
        try (PreparedStatement psVerificar = con.prepareStatement(sqlVerificar)) {
            psVerificar.setString(1, usuarioActual);
            psVerificar.setString(2, hashIngresado);
            ResultSet rs = psVerificar.executeQuery();
            
            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            int idUsuario = rs.getInt("id_usuario");
            
            // 🔍 PASO 2: Verificar que el nuevo nombre no exista ya en la BD
            String sqlCheckNombre = "SELECT id_usuario FROM usuarios WHERE username = ? AND id_usuario != ?";
            try (PreparedStatement psCheck = con.prepareStatement(sqlCheckNombre)) {
                psCheck.setString(1, nuevoUsuario);
                psCheck.setInt(2, idUsuario);
                ResultSet rsCheck = psCheck.executeQuery();
                
                if (rsCheck.next()) {
                    JOptionPane.showMessageDialog(this, "El nombre de usuario '" + nuevoUsuario + "' ya está en uso", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            
            // ✏️ PASO 3: Actualizar el nombre de usuario
            String sqlUpdate = "UPDATE usuarios SET username = ? WHERE id_usuario = ?";
            try (PreparedStatement psUpdate = con.prepareStatement(sqlUpdate)) {
                psUpdate.setString(1, nuevoUsuario);
                psUpdate.setInt(2, idUsuario);
                int filas = psUpdate.executeUpdate();
                
                if (filas > 0) {
                    JOptionPane.showMessageDialog(this, "✅ Nombre de usuario actualizado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    // 🔙 Volver a la configuración
                    config nueva = new config();
                    nueva.setLocationRelativeTo(null);
                    nueva.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al actualizar el nombre", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    

}

