/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package configuracion;

import Modelo.RespaldoUtil;
import Modelo.ConexionSQL;
import Modelo.baseInicial;
import java.io.File;
import java.sql.Connection;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author carlos
 */
public class Respaldo extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Respaldo() {
        initComponents();
        InitStyles();
        // 1. Evita que el usuario pueda estirar o maximizar la ventana
        this.setResizable(false); 
         // 2. Hace que NetBeans respete el tamaño exacto fijado en el Design
        this.pack(); 
        // 3. La centra en la pantalla (Siempre debe ir de última para que calcule el centro real)
        this.setLocationRelativeTo(null);
    }
        private void InitStyles() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));

        jButton7.setBackground(new java.awt.Color(21, 101, 192));
        jButton7.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Volver a Ajustes");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cloud-database-25.png"))); // NOI18N
        jButton8.setText("<html>\nCopia de Seguridad<br>\n<small style=\"font-weight: normal;\">Crear Copia de Seguridad de todos los documentos en DICI</small><br>\n</html>");
        jButton8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton8.setBorderPainted(false);
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton8.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton8.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dici16x16.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);

        title.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        title.setForeground(new java.awt.Color(153, 153, 153));
        title.setText("DICI Respaldo");

        title2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        title2.setForeground(new java.awt.Color(61, 61, 61));
        title2.setText("Bienvenido a Respaldo y Recuperación");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("<html> Al precionar el boton de creaar copia de seguridad se creara un respaldo de todos los documentos guardados<br>\nen la base de datos asi podra exportar todo DICI en su bolsillo para luego utilizar ese respaldo en otra computadora con DICI<br> </html>");

        jButton9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-cloud-database-25.png"))); // NOI18N
        jButton9.setText("<html>\nImportar Copia de Seguridad<br>\n<small style=\"font-weight: normal;\">Importar los documentos de una copia hecha desde DICI</small><br>\n</html>");
        jButton9.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 15, 1, 1, new java.awt.Color(0, 0, 0)));
        jButton9.setBorderPainted(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton9.setMaximumSize(new java.awt.Dimension(340, 50));
        jButton9.setPreferredSize(new java.awt.Dimension(150, 150));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(title2)
                        .addGroup(FondoLayout.createSequentialGroup()
                            .addComponent(jButton5)
                            .addGap(6, 6, 6)
                            .addComponent(title))
                        .addGroup(FondoLayout.createSequentialGroup()
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(title2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   // 1. Autenticar
    if (!autenticarUsuario()) {
        return;
    }
    
    // 2. Pedir contraseña para cifrar
    JPasswordField passField = new JPasswordField();
    Object[] message = {
        "🔐 Contraseña para cifrar el respaldo:",
        passField,
        "⚠️ Guarda esta contraseña o no podrás recuperar los datos"
    };
    
    int option = JOptionPane.showConfirmDialog(this, message, 
        "Contraseña de Seguridad", 
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (option != JOptionPane.OK_OPTION) {
        return;
    }
    
    String password = new String(passField.getPassword()).trim();
    if (password.isEmpty() || password.length() < 6) {
        JOptionPane.showMessageDialog(this, 
            "La contraseña debe tener al menos 6 caracteres", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 3. Confirmar contraseña
    JPasswordField confirmField = new JPasswordField();
    Object[] confirmMsg = {"Confirmar contraseña:", confirmField};
    option = JOptionPane.showConfirmDialog(this, confirmMsg, 
        "Confirmar Contraseña", 
        JOptionPane.OK_CANCEL_OPTION);
    
    if (option != JOptionPane.OK_OPTION) {
        return;
    }
    
    String confirm = new String(confirmField.getPassword()).trim();
    if (!password.equals(confirm)) {
        JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 4. Seleccionar archivo
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Guardar Copia de Seguridad");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivo DICI (*.dici)", "dici"));
    fileChooser.setSelectedFile(new File("respaldo_dici.dici"));
    
    if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
        File archivo = fileChooser.getSelectedFile();
        String ruta = archivo.getAbsolutePath();
        if (!ruta.toLowerCase().endsWith(".dici")) {
            archivo = new File(ruta + ".dici");
        }
        
        try {
            Connection con = ConexionSQL.getConexion();
            if (con != null) {
                RespaldoUtil.exportarRespaldo(con, archivo, password);
                JOptionPane.showMessageDialog(this, 
                    "✅ Respaldo cifrado creado exitosamente!\n" +
                    "Archivo: " + archivo.getName() + "\n" +
                    "🔐 No pierdas la contraseña",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al exportar: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
    // 1. Autenticar
    if (!autenticarUsuario()) {
        return;
    }
    
    // 2. Seleccionar archivo
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Seleccionar Copia de Seguridad");
    fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivo DICI (*.dici)", "dici"));
    
    if (fileChooser.showOpenDialog(this) != JFileChooser.APPROVE_OPTION) {
        return;
    }
    
    File archivo = fileChooser.getSelectedFile();
    
    // 3. Pedir contraseña
    JPasswordField passField = new JPasswordField();
    Object[] message = {"🔐 Contraseña del respaldo:", passField};
    
    int option = JOptionPane.showConfirmDialog(this, message, 
        "Contraseña de Seguridad", 
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (option != JOptionPane.OK_OPTION) {
        return;
    }
    
    String password = new String(passField.getPassword()).trim();
    if (password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "La contraseña es obligatoria", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 4. Confirmar (con mensaje claro de que NO se borran datos)
    int confirm = JOptionPane.showConfirmDialog(this,
        "📥 IMPORTACIÓN SEGURA\n\n" +
        "• Los datos existentes NO serán borrados\n" +
        "• Solo se agregarán datos nuevos\n" +
        "• Los documentos duplicados se renombrarán con (1), (2), etc.\n\n" +
        "¿Deseas continuar?",
        "Confirmar Importación",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.INFORMATION_MESSAGE);
        
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    // 5. Importar
    try {
        Connection con = ConexionSQL.getConexion();
        if (con != null) {
            RespaldoUtil.importarRespaldo(con, archivo, password);
        }
    } catch (Exception e) {
        String msg = e.getMessage();
        if (msg.contains("BadPadding") || msg.contains("Input length") || msg.contains("Contraseña incorrecta")) {
            msg = "❌ Contraseña incorrecta o archivo corrupto";
        }
        JOptionPane.showMessageDialog(this, 
            "Error al importar: " + msg, 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        config nueva = new config();
        nueva.setLocationRelativeTo(null);
        nueva.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.themes.FlatMacLightLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respaldo().setVisible(true);
            }
        });
    }
    
private boolean autenticarUsuario() {
    // Pedir usuario
    String usuario = JOptionPane.showInputDialog(this, 
        "Ingresa tu nombre de usuario:", 
        "Autenticación requerida", 
        JOptionPane.QUESTION_MESSAGE);
    
    if (usuario == null || usuario.trim().isEmpty()) {
        return false;
    }
    
    // Pedir contraseña
    JPasswordField passField = new JPasswordField();
    Object[] message = {"Contraseña:", passField};
    int option = JOptionPane.showConfirmDialog(this, message, 
        "Autenticación requerida", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.QUESTION_MESSAGE);
    
    if (option != JOptionPane.OK_OPTION) {
        return false;
    }
    
    String pass = new String(passField.getPassword()).trim();
    if (pass.isEmpty()) {
        return false;
    }
    
    // Verificar credenciales
    String hashIngresado = baseInicial.encriptarSHA256(pass);
    
    try (Connection con = ConexionSQL.getConexion()) {
        if (con == null) return false;
        
        String sql = "SELECT id_usuario FROM usuarios WHERE username = ? AND password = ?";
        try (java.sql.PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, usuario.trim());
            ps.setString(2, hashIngresado);
            java.sql.ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                return true;
            } else {
                JOptionPane.showMessageDialog(this, 
                    "❌ Usuario o contraseña incorrectos", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al autenticar: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
        return false;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fondo;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
